AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Lifecycle rules for Control Tower Log Archive buckets

Parameters:
  LogBucketName:
    Type: String
  AccessLogBucketName:
    Type: String

Resources:
  LogBucketLifecycle:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Ref LogBucketName
      LifecycleConfiguration:
        Rules:
          - Id: RetentionRule
            Status: Enabled
            Filter:
              Prefix: ""
            ExpirationInDays: 365
            NoncurrentVersionExpirationInDays: 365
          - Id: abort-incomplete-multipart
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
          - Id: delete-markers-cleanup
            Status: Enabled
            ExpiredObjectDeleteMarker: true

  AccessLogBucketLifecycle:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Ref AccessLogBucketName
      LifecycleConfiguration:
        Rules:
          - Id: RetentionRule
            Status: Enabled
            Filter:
              Prefix: ""
            ExpirationInDays: 365
            NoncurrentVersionExpirationInDays: 365
          - Id: abort-incomplete-multipart
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
          - Id: delete-markers-cleanup
            Status: Enabled
            ExpiredObjectDeleteMarker: true
